[versions]
# Gradle e Kotlin
androidGradlePlugin = "8.4.1"
kotlin = "2.0.21"
ksp = { id = "com.google.devtools.ksp", version = "2.0.0-1.0.21" }

# Hilt (Biblioteca)
hilt = "2.51.1"

# AndroidX e Jetpack
coreKtx = "1.13.1"
lifecycleRuntimeKtx = "2.8.0"
activityCompose = "1.9.0"

# Jetpack Compose
composeBom = "2024.05.00"

# Testes
junit = "4.13.2"
androidxTestJunit = "1.1.5"
espressoCore = "3.5.1"


[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Jetpack Compose (BOM)
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Hilt (Bibliotecas que serão usadas com 'implementation' e 'kapt')
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Testes
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }


[plugins]
# Plugins que SÃO gerenciados pelo TOML
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" } # <-- MUDANÇA: Adicionada esta linha

# Os plugins do Hilt e Kapt são omitidos daqui,
# pois você os definiu manualmente no build.gradle.kts raiz